### ISSUE TITLE
MFA job queue stuck

### ISSUE THREAD

**Issue by tshmak** [MontrealCorpusTools/Montreal-Forced-Aligner#294]
When running `mfa train`, I found that the aligner frequently gets "stuck" [here](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/blob/9f41e59737804ad24f514b5f25e48498e1b40479/montreal_forced_aligner/corpus/align_corpus.py#L203). 

It "frequently" gets stuck, but not always, even on the same dataset with exact configs (and same docker environment), which makes it very difficult to debug. Can someone provide some pointers as to what may have gone wrong and how to debug such multiprocessing Processes? 

Earlier, I had thought that restricting the number of processes with the `-j` option solved the problem, but it surfaced again. 

FYI, I'm running it on a server with 80 CPUs, but these are shared with others. Usually when I run MFA, the CPUs are 80% idle, and I'm only requesting 4 processes by `-j 4`. 

Your help is much appreciated.

**Comment by KinamSalad** [comment]
@tshmak  I have a similar problem (I don't know if it's the exact same problem)
I think the problem has to do with the python version.
Follow this link to create conda to install python3.8 : https://montreal-forced-aligner.readthedocs.io/en/latest/installation.html
Then I fixed the problem.

**Comment by tshmak** [comment]
I also followed the official installation instructions to install python 3.8.

**Comment by mmcauliffe** [comment]
I fixed a bug in the latest version where sometimes the queue would get processed too quickly and leave the workers unable to join.  If that's the cause of this issue, then it should be fixed by upgrading.

**Comment by tshmak** [comment]
Thanks for letting me know. I just tried, and the problem is still there. But thanks anyway!

**Comment by mmcauliffe** [comment]
This should be resolved at this point as several race conditions in multiprocessing have been fixed.
