### ISSUE TITLE
[BUG] TypeError: __init__() missing 1 required positional argument: 'words_symbols'

### ISSUE THREAD

**Issue by jeffmielke** [MontrealCorpusTools/Montreal-Forced-Aligner#828]
**Debugging checklist**

[x] Have you read the troubleshooting page (https://montreal-forced-aligner.readthedocs.io/en/latest/user_guide/troubleshooting.html) and searched the documentation to ensure that your issue is not addressed there?
[x] Have you updated to latest MFA version (check https://montreal-forced-aligner.readthedocs.io/en/latest/changelog/changelog_3.0.html)? What is the output of `mfa version`?
[x] Have you tried rerunning the command with the `--clean` flag?

**Describe the issue**

I updated to 3.1.3 to see how issue #824 was addressed and now I get an error message when trying to align the same test dataset that aligned successfully under 3.1.1: TypeError: __init__() missing 1 required positional argument: 'words_symbols'

**For Reproducing your issue**
Please fill out the following:

1. Corpus structure
   * What language is the corpus in? English
   * How many files/speakers? 8/8
   * Are you using lab files or TextGrid files for input? textgrid
2. Dictionary
   * Are you using a dictionary from MFA? If so, which one?
   * If it's a custom dictionary, what is the phoneset? arpabet
3. Acoustic model
   * If you're using an acoustic model, is it one download through MFA? If so, which one? english_us_arpa
   * If it's a model you've trained, what data was it trained on?

**Log file**
Please attach the log file for the run that encountered an error (by default these will be stored in `~/Documents/MFA`).

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, OSX, Linux] Linux
 - Version [e.g. MacOSX 10.15, Ubuntu 20.04, Windows 10, etc] Ubuntu 20.04
 - Any other details about the setup (Cloud, Docker, etc)
[compile_train_graphs.2.log](https://github.com/user-attachments/files/16253799/compile_train_graphs.2.log)
[compile_train_graphs.12.log](https://github.com/user-attachments/files/16253800/compile_train_graphs.12.log)
[compile_train_graphs.6.log](https://github.com/user-attachments/files/16253801/compile_train_graphs.6.log)
[compile_train_graphs.9.log](https://github.com/user-attachments/files/16253802/compile_train_graphs.9.log)
[compile_train_graphs.8.log](https://github.com/user-attachments/files/16253803/compile_train_graphs.8.log)
[compile_train_graphs.7.log](https://github.com/user-attachments/files/16253804/compile_train_graphs.7.log)
[compile_train_graphs.3.log](https://github.com/user-attachments/files/16253806/compile_train_graphs.3.log)
[compile_train_graphs.5.log](https://github.com/user-attachments/files/16253808/compile_train_graphs.5.log)
[compile_train_graphs.11.log](https://github.com/user-attachments/files/16253810/compile_train_graphs.11.log)
[compile_train_graphs.4.log](https://github.com/user-attachments/files/16253811/compile_train_graphs.4.log)
[compile_train_graphs.10.log](https://github.com/user-attachments/files/16253812/compile_train_graphs.10.log)
[compile_train_graphs.1.log](https://github.com/user-attachments/files/16253813/compile_train_graphs.1.log)

**Additional context**

Here is the whole error message:

 INFO     Compiling training graphs...                                          
Exception ignored in: <function TrainingGraphCompiler.__del__ at 0x7f22a185a160>
Traceback (most recent call last):
  File "/home/jimielke/.conda/envs/aligner/lib/python3.9/site-packages/kalpy/decoder/training_graphs.py", line 107, in __del__
    del self._compiler
AttributeError: _compiler
Exception ignored in: <function TrainingGraphCompiler.__del__ at 0x7f22a185a160>
Traceback (most recent call last):
  File "/home/jimielke/.conda/envs/aligner/lib/python3.9/site-packages/kalpy/decoder/training_graphs.py", line 107, in __del__
    del self._compiler
AttributeError: _compiler
Exception ignored in: <function TrainingGraphCompiler.__del__ at 0x7f22a185a160>
Traceback (most recent call last):
  File "/home/jimielke/.conda/envs/aligner/lib/python3.9/site-packages/kalpy/decoder/training_graphs.py", line 107, in __del__
    del self._compiler
AttributeError: _compiler
Exception ignored in: <function TrainingGraphCompiler.__del__ at 0x7f22a185a160>
Traceback (most recent call last):
  File "/home/jimielke/.conda/envs/aligner/lib/python3.9/site-packages/kalpy/decoder/training_graphs.py", line 107, in __del__
    del self._compiler
AttributeError: _compiler
Exception ignored in: <function TrainingGraphCompiler.__del__ at 0x7f22a185a160>
Traceback (most recent call last):
  File "/home/jimielke/.conda/envs/aligner/lib/python3.9/site-packages/kalpy/decoder/training_graphs.py", line 107, in __del__
    del self._compiler
AttributeError: _compiler
Exception ignored in: <function TrainingGraphCompiler.__del__ at 0x7f22a185a160>
Traceback (most recent call last):
  File "/home/jimielke/.conda/envs/aligner/lib/python3.9/site-packages/kalpy/decoder/training_graphs.py", line 107, in __del__
Exception ignored in: <function TrainingGraphCompiler.__del__ at 0x7f22a185a160>
Traceback (most recent call last):
  File "/home/jimielke/.conda/envs/aligner/lib/python3.9/site-packages/kalpy/decoder/training_graphs.py", line 107, in __del__
    del self._compiler
AttributeError: _compiler
    del self._compiler
AttributeError: _compiler
Exception ignored in: <function TrainingGraphCompiler.__del__ at 0x7f22a185a160>
Traceback (most recent call last):
  File "/home/jimielke/.conda/envs/aligner/lib/python3.9/site-packages/kalpy/decoder/training_graphs.py", line 107, in __del__
    del self._compiler
AttributeError: _compiler
Exception ignored in: <function TrainingGraphCompiler.__del__ at 0x7f22a185a160>
Traceback (most recent call last):
  File "/home/jimielke/.conda/envs/aligner/lib/python3.9/site-packages/kalpy/decoder/training_graphs.py", line 107, in __del__
    del self._compiler
AttributeError: _compiler
Exception ignored in: <function TrainingGraphCompiler.__del__ at 0x7f22a185a160>
Traceback (most recent call last):
  File "/home/jimielke/.conda/envs/aligner/lib/python3.9/site-packages/kalpy/decoder/training_graphs.py", line 107, in __del__
    del self._compiler
AttributeError: _compiler
Exception ignored in: <function TrainingGraphCompiler.__del__ at 0x7f22a185a160>
Traceback (most recent call last):
  File "/home/jimielke/.conda/envs/aligner/lib/python3.9/site-packages/kalpy/decoder/training_graphs.py", line 107, in __del__
    del self._compiler
AttributeError: _compiler
Exception ignored in: <function TrainingGraphCompiler.__del__ at 0x7f22a185a160>
Traceback (most recent call last):
  File "/home/jimielke/.conda/envs/aligner/lib/python3.9/site-packages/kalpy/decoder/training_graphs.py", line 107, in __del__
    del self._compiler
AttributeError: _compiler
 ERROR    There was an error in the run, please see the log.                    
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/jimielke/.conda/envs/aligner/bin/mfa", line 10, in <module>
    sys.exit(mfa_cli())
  File "/home/jimielke/.conda/envs/aligner/lib/python3.9/site-packages/rich_click/rich_command.py", line 367, in __call__
    return super().__call__(*args, **kwargs)
  File "/home/jimielke/.conda/envs/aligner/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/jimielke/.conda/envs/aligner/lib/python3.9/site-packages/rich_click/rich_command.py", line 152, in main
    rv = self.invoke(ctx)
  File "/home/jimielke/.conda/envs/aligner/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jimielke/.conda/envs/aligner/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jimielke/.conda/envs/aligner/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/jimielke/.conda/envs/aligner/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jimielke/.conda/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/command_line/align.py", line 121, in align_corpus_cli
    aligner.align()
  File "/home/jimielke/.conda/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/alignment/pretrained.py", line 363, in align
    super().align()
  File "/home/jimielke/.conda/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/alignment/base.py", line 366, in align
    self.compile_train_graphs()
  File "/home/jimielke/.conda/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/alignment/mixins.py", line 241, in compile_train_graphs
    for _ in run_kaldi_function(CompileTrainGraphsFunction, arguments):
  File "/home/jimielke/.conda/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/utils.py", line 732, in run_kaldi_function
    raise v
montreal_forced_aligner.exceptions.MultiprocessingError: MultiprocessingError:

Job 8 encountered an error:
Traceback (most recent call last):

  File "/home/jimielke/.conda/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/abc.py", line 104, in run
    self._run()

  File "/home/jimielke/.conda/envs/aligner/lib/python3.9/site-packages/montreal_forced_aligner/alignment/multiprocessing.py", line 445, in _run
    compiler = TrainingGraphCompiler(

TypeError: __init__() missing 1 required positional argument: 'words_symbols'

**Comment by mmcauliffe** [comment]
Should be fixed by https://github.com/conda-forge/montreal-forced-aligner-feedstock/pull/84, if you can run `conda update -c conda-forge montreal-forced-aligner` it should pick up the update to kalpy as well.

**Comment by jeffmielke** [comment]
Thanks. This worked for me.

**Comment by olafbrah** [comment]
I am having the same error still although I am using .txt files for my transcription files. I only seem to have this version on 3.2 but not on 2.2.17. 

` DEBUG    Beginning run for audio                                                 
 DEBUG    Using "global" profile                                                                  
 DEBUG    Using multiprocessing with 3                                                            
 DEBUG    Set up logger for MFA version: 3.2.0                                                    
 DEBUG    Cleaned previous run                                                                    
 DEBUG    There were some differences in the current run compared to the last one. This may cause 
          issues, run with --clean, if you hit an error.                                          
 DEBUG    Loaded dictionary in 5.926 seconds                                                      
 INFO     Setting up corpus information...                                                        
 DEBUG    Could not load from temp                                                                
 INFO     Loading corpus from source files...                                                     
 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 304/100  [ 0:00:00 < 0:00:00 , ? it/s ] DEBUG    Processing queue: 0.19272704300000143                                                   
 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400/100  [ 0:00:00 < 0:00:00 , 90 it/s ]
 DEBUG    Parsed corpus directory with 3 jobs in 0.23261309600000146 seconds                      
 INFO     Found 1 speaker across 400 files, average number of utterances per speaker: 400.0       
 DEBUG    Loaded corpus in 1.190 seconds                                                          
 INFO     Initializing multiprocessing jobs...                                                    
 DEBUG    Initialized jobs in 0.016 seconds                                                       
 INFO     Normalizing text...                                                                     
 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400/400  [ 0:00:01 < 0:00:00 , ? it/s ]
 DEBUG    Wrote lexicon information in 4.236 seconds                                              
 INFO     Generating MFCCs...                                                                     
 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400/400  [ 0:00:05 < 0:00:00 , ? it/s ]
 DEBUG    Generating MFCCs took 5.473 seconds                                                     
 INFO     Calculating CMVN...                                                                     
 INFO     Generating final features...                                                            
 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400/400  [ 0:00:01 < 0:00:00 , ? it/s ]
 DEBUG    Generating final features took 1.173 seconds                                            
 INFO     Creating corpus split...                                                                
 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400/400  [ 0:00:01 < 0:00:00 , ? it/s ]
 DEBUG    Generated features in 7.815 seconds                                                     
 DEBUG    Setting up corpus took 24.881 seconds                                                   
 DEBUG                                                                                            
 DEBUG    ====ACOUSTIC MODEL INFO====                                                             
 DEBUG    Acoustic model root directory: /home/albert/Documents/MFA/extracted_models/acoustic     
 DEBUG    Acoustic model dirname:                                                                 
          /home/albert/Documents/MFA/extracted_models/acoustic/english_mfa_acoustic               
 DEBUG    Acoustic model meta path:                                                               
          /home/albert/Documents/MFA/extracted_models/acoustic/english_mfa_acoustic/meta.json     
 DEBUG    Acoustic model meta information:                                                        
 DEBUG    architecture: gmm-hmm                                                                   
          dictionaries:                                                                           
            bracketed_word: '[bracketed]'                                                         
            clitic_marker: ''''                                                                   
            default: default                                                                      
            laughter_word: '[laughter]'                                                           
            names:                                                                                
            - default                                                                             
            - english_india_mfa                                                                   
            - english_nigeria_mfa                                                                 
            - english_uk_mfa                                                                      
            - english_us_mfa                                                                      
            - nonnative                                                                           
            oov_word: <unk>                                                                       
            position_dependent_phones: false                                                      
            silence_word: <eps>                                                                   
            use_g2p: false                                                                        
          features:                                                                               
            cepstral_lifter: 22                                                                   
            delta_pitch: 0.005                                                                    
            dither: 0.0001                                                                        
            energy_floor: 1.0                                                                     
            feature_type: mfcc                                                                    
            frame_length: 25                                                                      
            frame_shift: 10                                                                       
            high_frequency: 7800                                                                  
            low_frequency: 20                                                                     
            max_f0: 800                                                                           
            min_f0: 50                                                                            
            num_coefficients: 13                                                                  
            num_mel_bins: 23                                                                      
            penalty_factor: 0.1                                                                   
            preemphasis_coefficient: 0.97                                                         
            sample_frequency: 16000                                                               
            silence_weight: 0.0                                                                   
            snip_edges: false                                                                     
            splice_left_context: 3                                                                
            splice_right_context: 3                                                               
            use_energy: true                                                                      
            use_pitch: false                                                                      
            use_voicing: false                                                                    
            uses_cmvn: true                                                                       
            uses_deltas: false                                                                    
            uses_speaker_adaptation: true                                                         
            uses_splices: true                                                                    
            uses_voiced: false                                                                    
          final_non_silence_correction: 0.2966666666666667                                        
          final_silence_correction: 0.99                                                          
          initial_silence_probability: 0.17                                                       
          language: unknown                                                                       
          oov_phone: spn                                                                          
          optional_silence_phone: sil                                                             
          phone_groups:                                                                           
            '0':                                                                                  
            - kp                                                                                  
            - p                                                                                   
            - "p\u02B0"                                                                           
            - "p\u02B2"                                                                           
            - "p\u02B7"                                                                           
            '1':                                                                                  
            - b                                                                                   
            - "b\u02B2"                                                                           
            - "\u0261b"                                                                           
            '10':                                                                                 
            - d                                                                                   
            - "d\u02B2"                                                                           
            - "\u0256"                                                                            
            '11':                                                                                 
            - "\u027E"                                                                            
            - "\u027E\u02B2"                                                                      
            '12':                                                                                 
            - "t\u0283"                                                                           
            '13':                                                                                 
            - "d\u0292"                                                                           
            '14':                                                                                 
            - "\u0283"                                                                            
            '15':                                                                                 
            - "\u0292"                                                                            
            '16':                                                                                 
            - s                                                                                   
            '17':                                                                                 
            - z                                                                                   
            '18':                                                                                 
            - "\u0279"                                                                            
            '19':                                                                                 
            - m                                                                                   
            - "m\u0329"                                                                           
            '2':                                                                                  
            - f                                                                                   
            - "f\u02B2"                                                                           
            - "f\u02B7"                                                                           
            '20':                                                                                 
            - "m\u02B2"                                                                           
            '21':                                                                                 
            - "\u0271"                                                                            
            '22':                                                                                 
            - n                                                                                   
            - "n\u0329"                                                                           
            '23':                                                                                 
            - "\u0272"                                                                            
            '24':                                                                                 
            - "\u027E\u0303"                                                                      
            '25':                                                                                 
            - "\u014B"                                                                            
            '26':                                                                                 
            - l                                                                                   
            '27':                                                                                 
            - "\u026B"                                                                            
            - "\u026B\u0329"                                                                      
            '28':                                                                                 
            - "\u028E"                                                                            
            '29':                                                                                 
            - "\u025F"                                                                            
            - "\u025F\u02B7"                                                                      
            - "\u0261"                                                                            
            - "\u0261\u02B7"                                                                      
            '3':                                                                                  
            - v                                                                                   
            - "v\u02B2"                                                                           
            - "v\u02B7"                                                                           
            '30':                                                                                 
            - c                                                                                   
            - "c\u02B0"                                                                           
            - "c\u02B7"                                                                           
            '31':                                                                                 
            - k                                                                                   
            - "k\u02B0"                                                                           
            - "k\u02B7"                                                                           
            '32':                                                                                 
            - "\xE7"                                                                              
            '33':                                                                                 
            - h                                                                                   
            '34':                                                                                 
            - "\u0250"                                                                            
            - "\u0259"                                                                            
            '35':                                                                                 
            - "\u025C"                                                                            
            - "\u025C\u02D0"                                                                      
            '36':                                                                                 
            - "\u025A"                                                                            
            - "\u025D"                                                                            
            '37':                                                                                 
            - "\u028A"                                                                            
            '38':                                                                                 
            - "\u026A"                                                                            
            '39':                                                                                 
            - "\u0251"                                                                            
            - "\u0251\u02D0"                                                                      
            '4':                                                                                  
            - "\u03B8"                                                                            
            '40':                                                                                 
            - "\u0252"                                                                            
            - "\u0252\u02D0"                                                                      
            - "\u0254"                                                                            
            '41':                                                                                 
            - a                                                                                   
            - "a\u02D0"                                                                           
            '42':                                                                                 
            - "\xE6"                                                                              
            '43':                                                                                 
            - aj                                                                                  
            '44':                                                                                 
            - aw                                                                                  
            '45':                                                                                 
            - i                                                                                   
            - "i\u02D0"                                                                           
            '46':                                                                                 
            - j                                                                                   
            '47':                                                                                 
            - "\u025B"                                                                            
            - "\u025B\u02D0"                                                                      
            '48':                                                                                 
            - e                                                                                   
            - ej                                                                                  
            - "e\u02D0"                                                                           
            '49':                                                                                 
            - "\u0289"                                                                            
            - "\u0289\u02D0"                                                                      
            '5':                                                                                  
            - "t\u032A"                                                                           
            '50':                                                                                 
            - u                                                                                   
            - "u\u02D0"                                                                           
            '51':                                                                                 
            - w                                                                                   
            '52':                                                                                 
            - "\u028B"                                                                            
            '53':                                                                                 
            - "\u0254j"                                                                           
            '54':                                                                                 
            - o                                                                                   
            - ow                                                                                  
            - "o\u02D0"                                                                           
            - "\u0259w"                                                                           
            '6':                                                                                  
            - "\xF0"                                                                              
            '7':                                                                                  
            - "d\u032A"                                                                           
            '8':                                                                                  
            - t                                                                                   
            - "t\u02B0"                                                                           
            - "t\u02B2"                                                                           
            - "t\u02B7"                                                                           
            - "\u0288"                                                                            
            - "\u0288\u02B2"                                                                      
            - "\u0288\u02B7"                                                                      
            '9':                                                                                  
            - "\u0294"                                                                            
          phone_mapping:                                                                          
            <eps>: 0                                                                              
            a: 3                                                                                  
            aj: 4                                                                                 
            aw: 5                                                                                 
            "a\u02D0": 6                                                                          
            b: 7                                                                                  
            "b\u02B2": 8                                                                          
            c: 9                                                                                  
            "c\u02B0": 10                                                                         
            "c\u02B7": 11                                                                         
            d: 12                                                                                 
            "d\u0292": 13                                                                         
            "d\u02B2": 14                                                                         
            "d\u032A": 15                                                                         
            e: 16                                                                                 
            ej: 17                                                                                
            "e\u02D0": 18                                                                         
            f: 19                                                                                 
            "f\u02B2": 20                                                                         
            "f\u02B7": 21                                                                         
            h: 22                                                                                 
            i: 23                                                                                 
            "i\u02D0": 24                                                                         
            j: 25                                                                                 
            k: 26                                                                                 
            kp: 27                                                                                
            "k\u02B0": 28                                                                         
            "k\u02B7": 29                                                                         
            l: 30                                                                                 
            m: 31                                                                                 
            "m\u02B2": 32                                                                         
            "m\u0329": 33                                                                         
            n: 34                                                                                 
            "n\u0329": 35                                                                         
            o: 36                                                                                 
            ow: 37                                                                                
            "o\u02D0": 38                                                                         
            p: 39                                                                                 
            "p\u02B0": 40                                                                         
            "p\u02B2": 41                                                                         
            "p\u02B7": 42                                                                         
            s: 43                                                                                 
            sil: 1                                                                                
            spn: 2                                                                                
            t: 44                                                                                 
            "t\u0283": 45                                                                         
            "t\u02B0": 46                                                                         
            "t\u02B2": 47                                                                         
            "t\u02B7": 48                                                                         
            "t\u032A": 49                                                                         
            u: 50                                                                                 
            "u\u02D0": 51                                                                         
            v: 52                                                                                 
            "v\u02B2": 53                                                                         
            "v\u02B7": 54                                                                         
            w: 55                                                                                 
            z: 56                                                                                 
            "\xE6": 57                                                                            
            "\xE7": 58                                                                            
            "\xF0": 59                                                                            
            "\u014B": 60                                                                          
            "\u0250": 61                                                                          
            "\u0251": 62                                                                          
            "\u0251\u02D0": 63                                                                    
            "\u0252": 64                                                                          
            "\u0252\u02D0": 65                                                                    
            "\u0254": 66                                                                          
            "\u0254j": 67                                                                         
            "\u0256": 68                                                                          
            "\u0259": 69                                                                          
            "\u0259w": 70                                                                         
            "\u025A": 71                                                                          
            "\u025B": 72                                                                          
            "\u025B\u02D0": 73                                                                    
            "\u025C": 74                                                                          
            "\u025C\u02D0": 75                                                                    
            "\u025D": 76                                                                          
            "\u025F": 77                                                                          
            "\u025F\u02B7": 78                                                                    
            "\u0261": 79                                                                          
            "\u0261b": 80                                                                         
            "\u0261\u02B7": 81                                                                    
            "\u026A": 82                                                                          
            "\u026B": 83                                                                          
            "\u026B\u0329": 84                                                                    
            "\u0271": 85                                                                          
            "\u0272": 86                                                                          
            "\u0279": 87                                                                          
            "\u027E": 88                                                                          
            "\u027E\u02B2": 89                                                                    
            "\u027E\u0303": 90                                                                    
            "\u0283": 91                                                                          
            "\u0288": 92                                                                          
            "\u0288\u02B2": 93                                                                    
            "\u0288\u02B7": 94                                                                    
            "\u0289": 95                                                                          
            "\u0289\u02D0": 96                                                                    
            "\u028A": 97                                                                          
            "\u028B": 98                                                                          
            "\u028E": 99                                                                          
            "\u0292": 100                                                                         
            "\u0294": 101                                                                         
            "\u03B8": 102                                                                         
          phone_set_type: UNKNOWN                                                                 
          phone_type: triphone                                                                    
          phones: !!set                                                                           
            a: null                                                                               
            aj: null                                                                              
            aw: null                                                                              
            "a\u02D0": null                                                                       
            b: null                                                                               
            "b\u02B2": null                                                                       
            c: null                                                                               
            "c\u02B0": null                                                                       
            "c\u02B7": null                                                                       
            d: null                                                                               
            "d\u0292": null                                                                       
            "d\u02B2": null                                                                       
            "d\u032A": null                                                                       
            e: null                                                                               
            ej: null                                                                              
            "e\u02D0": null                                                                       
            f: null                                                                               
            "f\u02B2": null                                                                       
            "f\u02B7": null                                                                       
            h: null                                                                               
            i: null                                                                               
            "i\u02D0": null                                                                       
            j: null                                                                               
            k: null                                                                               
            kp: null                                                                              
            "k\u02B0": null                                                                       
            "k\u02B7": null                                                                       
            l: null                                                                               
            m: null                                                                               
            "m\u02B2": null                                                                       
            "m\u0329": null                                                                       
            n: null                                                                               
            "n\u0329": null                                                                       
            o: null                                                                               
            ow: null                                                                              
            "o\u02D0": null                                                                       
            p: null                                                                               
            "p\u02B0": null                                                                       
            "p\u02B2": null                                                                       
            "p\u02B7": null                                                                       
            s: null                                                                               
            t: null                                                                               
            "t\u0283": null                                                                       
            "t\u02B0": null                                                                       
            "t\u02B2": null                                                                       
            "t\u02B7": null                                                                       
            "t\u032A": null                                                                       
            u: null                                                                               
            "u\u02D0": null                                                                       
            v: null                                                                               
            "v\u02B2": null                                                                       
            "v\u02B7": null                                                                       
            w: null                                                                               
            z: null                                                                               
            "\xE6": null                                                                          
            "\xE7": null                                                                          
            "\xF0": null                                                                          
            "\u014B": null                                                                        
            "\u0250": null                                                                        
            "\u0251": null                                                                        
            "\u0251\u02D0": null                                                                  
            "\u0252": null                                                                        
            "\u0252\u02D0": null                                                                  
            "\u0254": null                                                                        
            "\u0254j": null                                                                       
            "\u0256": null                                                                        
            "\u0259": null                                                                        
            "\u0259w": null                                                                       
            "\u025A": null                                                                        
            "\u025B": null                                                                        
            "\u025B\u02D0": null                                                                  
            "\u025C": null                                                                        
            "\u025C\u02D0": null                                                                  
            "\u025D": null                                                                        
            "\u025F": null                                                                        
            "\u025F\u02B7": null                                                                  
            "\u0261": null                                                                        
            "\u0261b": null                                                                       
            "\u0261\u02B7": null                                                                  
            "\u026A": null                                                                        
            "\u026B": null                                                                        
            "\u026B\u0329": null                                                                  
            "\u0271": null                                                                        
            "\u0272": null                                                                        
            "\u0279": null                                                                        
            "\u027E": null                                                                        
            "\u027E\u02B2": null                                                                  
            "\u027E\u0303": null                                                                  
            "\u0283": null                                                                        
            "\u0288": null                                                                        
            "\u0288\u02B2": null                                                                  
            "\u0288\u02B7": null                                                                  
            "\u0289": null                                                                        
            "\u0289\u02D0": null                                                                  
            "\u028A": null                                                                        
            "\u028B": null                                                                        
            "\u028E": null                                                                        
            "\u0292": null                                                                        
            "\u0294": null                                                                        
            "\u03B8": null                                                                        
          silence_probability: 0.17                                                               
          train_date: '2024-06-12 12:16:18.584033'                                                
          training:                                                                               
            audio_duration: 12862940.052134357                                                    
            average_log_likelihood: -0.08382050453507844                                          
            num_oovs: 0                                                                           
            num_speakers: 75018                                                                   
            num_utterances: 2374755                                                               
          version: 3.1.0                                                                          
                                                                                                  
 DEBUG                                                                                            
 DEBUG    Setup for alignment in 25.020 seconds                                                   
 INFO     Compiling training graphs...                                                            
Exception ignored in: <function TrainingGraphCompiler.__del__ at 0x7f473fa02670>
Traceback (most recent call last):
  File "/home/albert/miniconda3/envs/mfa_3/lib/python3.8/site-packages/kalpy/decoder/training_graphs.py", line 107, in __del__
    del self._compiler
AttributeError: _compiler
Exception ignored in: <function TrainingGraphCompiler.__del__ at 0x7f473fa02670>
Traceback (most recent call last):
  File "/home/albert/miniconda3/envs/mfa_3/lib/python3.8/site-packages/kalpy/decoder/training_graphs.py", line 107, in __del__
    del self._compiler
AttributeError: _compiler
Exception ignored in: <function TrainingGraphCompiler.__del__ at 0x7f473fa02670>
Traceback (most recent call last):
  File "/home/albert/miniconda3/envs/mfa_3/lib/python3.8/site-packages/kalpy/decoder/training_graphs.py", line 107, in __del__
    del self._compiler
AttributeError: _compiler
 ERROR    There was an error in the run, please see the log.                                      
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/albert/miniconda3/envs/mfa_3/bin/mfa", line 10, in <module>
    sys.exit(mfa_cli())
  File "/home/albert/miniconda3/envs/mfa_3/lib/python3.8/site-packages/rich_click/rich_command.py", line 367, in __call__
    return super().__call__(*args, **kwargs)
  File "/home/albert/miniconda3/envs/mfa_3/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/albert/miniconda3/envs/mfa_3/lib/python3.8/site-packages/rich_click/rich_command.py", line 152, in main
    rv = self.invoke(ctx)
  File "/home/albert/miniconda3/envs/mfa_3/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/albert/miniconda3/envs/mfa_3/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/albert/miniconda3/envs/mfa_3/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/albert/miniconda3/envs/mfa_3/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/albert/miniconda3/envs/mfa_3/lib/python3.8/site-packages/montreal_forced_aligner/command_line/align.py", line 121, in align_corpus_cli
    aligner.align()
  File "/home/albert/miniconda3/envs/mfa_3/lib/python3.8/site-packages/montreal_forced_aligner/alignment/pretrained.py", line 363, in align
    super().align()
  File "/home/albert/miniconda3/envs/mfa_3/lib/python3.8/site-packages/montreal_forced_aligner/alignment/base.py", line 366, in align
    self.compile_train_graphs()
  File "/home/albert/miniconda3/envs/mfa_3/lib/python3.8/site-packages/montreal_forced_aligner/alignment/mixins.py", line 241, in compile_train_graphs
    for _ in run_kaldi_function(CompileTrainGraphsFunction, arguments):
  File "/home/albert/miniconda3/envs/mfa_3/lib/python3.8/site-packages/montreal_forced_aligner/utils.py", line 739, in run_kaldi_function
    raise v
montreal_forced_aligner.exceptions.MultiprocessingError: MultiprocessingError:

Job 1 encountered an error:
Traceback (most recent call last):

  File "/home/albert/miniconda3/envs/mfa_3/lib/python3.8/site-packages/montreal_forced_aligner/abc.py", line 104, in run
    self._run()

  File "/home/albert/miniconda3/envs/mfa_3/lib/python3.8/site-packages/montreal_forced_aligner/alignment/multiprocessing.py", line 457, in _run
    compiler = TrainingGraphCompiler(

TypeError: __init__() missing 1 required positional argument: 'words_symbols'`

**Comment by sidleal** [comment]
Hi there, I was facing the same error here, but I could fix it after checking the commit cited earlier in this thread.
In my case the kalpy lib was on version 0.6.3, so I run:
```` conda update -c conda-forge kalpy ````
And so it was upgraded to 0.6.5... after that, all commands are working again.

**Comment by olafbrah** [comment]
> Hi there, I was facing the same error here, but I could fix it after checking the commit cited earlier in this thread. In my case the kalpy lib was on version 0.6.3, so I run: `conda update -c conda-forge kalpy` And so it was upgraded to 0.6.5... after that, all commands are working again.

Thanks! That fixed it

**Comment by HamidMojarrad** [comment]
> Hi there, I was facing the same error here, but I could fix it after checking the commit cited earlier in this thread. In my case the kalpy lib was on version 0.6.3, so I run: `conda update -c conda-forge kalpy` And so it was upgraded to 0.6.5... after that, all commands are working again.

It resolved the issue. Thanks for sharing.

**Comment by kalimandfas** [comment]
good good ,i am so happy,i was confused by it
